M48
; DRILL file {KiCad 8.0.3} date 2024-07-06T23:57:49+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-06T23:57:49+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X75.51Y-174.57
X81.29Y-174.57
T2
X63.0Y-93.0
X63.0Y-178.0
X106.0Y-93.0
X106.0Y-178.0
M30
